### ISSUE TITLE
Question: is this based on Paranoid library?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [LSPosed/LSParanoid#1]
This:
https://github.com/MichaelRocks/paranoid/

It seems very similar, and yet there is no mention about it, and no credit...
I ask because I'm thinking of migrating away from it, and I think it might be quite easy to do it if it's about the same...

**Comment by yujincheng08** [comment]
mentioned in the license

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 I don't see it here:
https://github.com/LSPosed/LSParanoid#license
and not here:
https://github.com/LSPosed/LSParanoid/blob/master/LICENSE.txt

No mention of the original repository, and no mention of "MichaelRocks" who made it.
Only mention of "MichaelRocks" is in the "Contributors" part.

**Comment by yujincheng08** [comment]
Does apache 2.0 require mentioning the original repository? Following Apache 2.0, I kept the original license and author. I also kept all the historical commits.

**Comment by AndroidDeveloperLB** [comment]
No, but it's nice, and I wanted to see if migration would be easy

**Comment by yujincheng08** [comment]
Basically, I think license applies to all sources, and it's a better way to credit the original author. But as you required, I added credits to the Readme. Thanks you anyway.

**Comment by AndroidDeveloperLB** [comment]
Thank you!
