### ISSUE TITLE
Improvements: Instructions how to include the plugin to Gradle (Grove)

### ISSUE THREAD

**Issue by eakteam** [LSPosed/LSParanoid#10]
The way of implementation is kinda weird and don't follow standart guidelines... Maybe it is modern but there are some rare cases where we can't implement the library in that way.

Can you please provide some instructions how to implement the plugin in standart way via build.gradle & app.gradle file using Grove language and not KTS ?

**Comment by vvb2060** [comment]
https://docs.gradle.org/current/userguide/plugins.html
