### ISSUE TITLE
Version 0.5.0 doesn't exist on MavenCentral

### ISSUE THREAD

**Issue by eakteam** [LSPosed/LSParanoid#11]
The latest version is not uploaded on Maven Central

**Comment by yujincheng08** [comment]
uploaded

**Comment by eakteam** [comment]
> uploaded

Thanks, testing right now...

**Comment by eakteam** [comment]
> uploaded

Are you sure?

```
> Could not resolve all files for configuration ':classpath'.
   > Could not find org.lsposed.lsparanoid:gradle-plugin:0.5.0.
```

**Comment by yujincheng08** [comment]
https://repo.maven.apache.org/maven2/org/lsposed/lsparanoid/gradle-plugin/0.5.0/

Yes, pretty sure.

**Comment by eakteam** [comment]
> Member

Yes, now it works, testing it for Dynamic Feature Modules. :)
