### ISSUE TITLE
Cannot use the plugin to App Dynamic Feature Modules. Sample Project Attached

### ISSUE THREAD

**Issue by eakteam** [LSPosed/LSParanoid#12]
Hello, something wrong when trying to implement this plugin to app's modules. It doesn't works and throws `Unresolved Reference`

On the default app's class files it seems to works fine but on the dynamic feature module's classes it can't be imported. 

Please see the attached project below

[LSParanoid.zip](https://github.com/LSPosed/LSParanoid/files/10778282/LSParanoid.zip)

**Comment by vvb2060** [comment]
you are using an old version

**Comment by eakteam** [comment]
> you are using an old version

The new version cannot be downloaded, it says doesn't exist on maven.
