### ISSUE TITLE
Incompatible with AGP 8

### ISSUE THREAD

**Issue by androidacy-user** [LSPosed/LSParanoid#25]
Hello!

AGP 8 is now recommended for stable versions of android studio, however, with AGP 8, this plugin causes issues because it relies on gradle-api:7.4.2.

For example:

```
Unresolved reference: generateLocaleConfig
```

This is a feature dependent on AGP 8+ that our project relies on.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSParanoid/commit/90606653dcf7c9bc950f4d2faa2e4ffb3092e7bf
