### ISSUE TITLE
Include Modules

### ISSUE THREAD

**Issue by eakteam** [LSPosed/LSParanoid#4]
The original Paranoid have an option like : 

```
lsparanoid {
            includeSubprojects = true
        }
```

This enhanced version of Paranoid doesn't support it. So i just want to ask if this is something that it does in background without needed of this option or it doesn't support it at all? Thanks

**Comment by yujincheng08** [comment]
it causes #3

**Comment by yujincheng08** [comment]
the old transform API provides a way to distinguish project classes and dependencies classes. the new API does not.

**Comment by eakteam** [comment]
Thanks for your reply, but if we include the plugin to Dynamic Feature Modules does it work or not?
