### ISSUE TITLE
Execution failed for task ':app:lsparanoidRelease'.

### ISSUE THREAD

**Issue by kwaiching** [LSPosed/LSParanoid#42]
Execution failed for task ':app:lsparanoidRelease'.
> Cannot fingerprint input property 'classFilter': value 'build_9o62u5w6w5nfzy3sk2zk5iizg$_run_closure1$_closure4$_closure5@1e646ca7' cannot be serialized.

**Comment by JasonKhew96** [comment]
use `assembleRelease` with `lsparanoid.variantFilter`
