### ISSUE TITLE
It doesn't work with modules (dynamic feature modules)

### ISSUE THREAD

**Issue by eakteam** [LSPosed/LSParanoid#5]
I have added to class path : 
`classpath ("org.lsposed.lsparanoid:gradle-plugin:0.4.4")`

Module build gradle file: 
`apply plugin: "org.lsposed.lsparanoid"`

```
lsparanoid {
            enabled = true
            //includeSubprojects = true
            global = true
        }
```

Seems to works fine, but when i try to import the class for `@Obfuscate` inside a module's kotlin file it seems to not being able to recognize the plugin. It says me to import `classpath ("org.lsposed.lsparanoid:gradle-plugin:0.4.4")` to the class path, but it is currently added.

```
@Obfuscate
class testClass: testClassAbstract() {

}
```

It throws unresolved reference

**Comment by vvb2060** [comment]
add dependent

**Comment by eakteam** [comment]
@vvb2060 , @yujincheng08 will this feature be available? Because most of Android project are supporting dynamic feature modules so without that support it is useless.

P.s original Paranoid works great with modules.

**Comment by yujincheng08** [comment]
any example project that reproduces it?

BTW, you hv set global = true. Using annotation then is meaningless.

**Comment by eakteam** [comment]
@yujincheng08 the project is huge. But can be reproduced in simple ways.

Create an Android project and add '@Obfuscate' to the main class activity/fragment.

Add a dynamic feature module to this android project and try to add '@Obfuscate' anotation to any kotlin/java class file inside that dynamic feature module.

**Comment by eakteam** [comment]
@yujincheng08 the dynamic feature modules contains: `apply plugin: "com.android.dynamic-feature"` but i see that you have disabled the ability to obfuscate `android-library` too?

So this plugin only obfuscate app class files and not modules or library classes?

**Comment by yujincheng08** [comment]
0.4.5 shod work
