### ISSUE TITLE
Question: Why "classpath("com.android.tools.build:gradle")" is commented?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [LSPosed/LSParanoid#6]
On the instructions, it says this:

```
    dependencies {
        classpath("org.lsposed.lsparanoid:gradle-plugin:0.4.4")
        // classpath("com.android.tools.build:gradle")
    }
```

Why the comment? It's actually an important part, no? 
Is it to show that it's supposed to be before?
Or the order doesn't matter? 
Please explain.

**Comment by yujincheng08** [comment]
order does not matter now.

and we don't want to hard code AGP since we don't want to specify a version name

**Comment by AndroidDeveloperLB** [comment]
I don't understand. Why is it commented?
Should it be removed?

**Comment by yujincheng08** [comment]
commected because theres no verson name

does not mean it should be removed

**Comment by AndroidDeveloperLB** [comment]
So I can ignore it, right?
I already know it's needed...
It's just misleading as I never saw such a thing on other repositories.
Including the one that this one is based on:
https://github.com/MichaelRocks/paranoid

**Comment by AndroidDeveloperLB** [comment]
Anyway, please consider removing the comment, or change it to being uncommented. It's confusing...

**Comment by yujincheng08** [comment]
no

if we remove the comment, we need to specify a version name, and this will confuse user that the plugin only works on a specific version of AGP

and the original repo does not even mention that you have to add AGP as dependency, which is more confusing.

**Comment by AndroidDeveloperLB** [comment]
Why do you need to specify the version name? You can just remove it completely, and show only the dependency of the repository.

It's already one of the basic things you have when you create an Android app project. This is what I get from the wizard of Android Studio. Today the structure of a new project even changed. It's not with "classpath" anymore, no?

Putting a comment shows as if you want to get rid of it. It has nothing to do with the version. Putting a comment means it won't be included.

Why do you add it? I never saw on any other repository a comment of an existing dependency, with the explanation that it shouldn't be commented. Why comment and say it shouldn't be commented...
I don't understand.

**Comment by yujincheng08** [comment]
aha. because we need AGP.

I know theres no more classpath now. we will make it morden.

**Comment by AndroidDeveloperLB** [comment]
But AGP was already added to every new Android project. 
And this library is for Android projects, so developers should know it's supposed to be there.
Yet, instead, I see it being commented, as if this repository replaces this dependency. Commenting a dependency doesn't mean that it's without a version. Commenting it means it's not used. This is confusing...
Repositories that want to mention a dependency without a version will just say it. They won't use a comment of a different dependency. 

The dependency of the repository has a version, too, even though it doesn't have to have it.

Here, examples of Android repositories that don't mention AGP, as it makes sense that it's needed already:

https://github.com/MichaelRocks/libphonenumber-android
https://github.com/aws-amplify/aws-sdk-android
https://github.com/hdodenhof/CircleImageView
