### ISSUE TITLE
Request: support for android-library too

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [LSPosed/LSParanoid#7]
In the original repository, it wasn't officially offered, but I was given a workaround to let it work:

https://github.com/MichaelRocks/paranoid/issues/38

We added this to the dependencies (and probably something else too, I don't remember):

```
api("io.michaelrocks:paranoid-core:0.3.7")
```

Also not using "const":

 https://github.com/MichaelRocks/paranoid/issues/61

I don't think we can use the dependency workaround now. What can we use instead?
Also do we still need the no-"const" workaround?

**Comment by yujincheng08** [comment]
implementation("org.lsposed.lsparanoid:core:0.4.5")

**Comment by AndroidDeveloperLB** [comment]
I think I got a similar workaround . I used this instead:

```
classpath("org.lsposed.lsparanoid:gradle-plugin:0.4.4")
```

And this in the library module:
```
api("org.lsposed.lsparanoid:core:0.4.4")
```

I still need to perform some testing, but at least it gets built fine.
Also, not sure why, but I saw "0.4.5" being mentioned, yet it doesn't work. Only 0.4.4.

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 Should the "0.4.5" match on both cases?
Meaning :

```
classpath("org.lsposed.lsparanoid:gradle-plugin:0.4.5")
```
And:
```
implementation("org.lsposed.lsparanoid:core:0.4.5")
```

**Comment by AndroidDeveloperLB** [comment]
Later I got it fine in building, but obfuscation doesn't work (on the AAR library module) :
https://github.com/MichaelRocks/paranoid/issues/38

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 After reporting that it's not working, the issue was closed without me verifying:
https://github.com/LSPosed/LSParanoid/issues/8#issuecomment-1436034160

I don't see in the link anything similar to AAR library. And all is in kts format which isn't the mainstream yet...
Please help...
On the original repository the developer helped and didn't close without letting to reply...

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/219964036-c696041b-74c4-4f91-b1d6-2cc7b9973cf8.png)

But I saw aar's.

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/219964202-6b8b05b4-dfe6-400d-93a7-368b69aef50a.png)
And I saw the arr's being obfuscated.

You should confirm your issue before asking. And without any helpful information we cannot help you :)

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 Thank you for restoring my way to communicate here. Please let me check it out further. 
I will try it out again after checking what you've provided.
Please let's continue the conversation there.

From what it seems right now, though, it doesn't look like what I'm working with. 
I think "library-may-obfuscate" is the most similar, but I don't see "classpath" there for example. I will try to mimic what's there. Sorry to upset you.

**Comment by yujincheng08** [comment]
Be aware that samples are for 0.5.0, but it's not yet released. You can follow the Github Action workflow to mimic the samples.

**Comment by yujincheng08** [comment]
The simpliest way to use snapshot 0.5.0 is to download the github action artifacts and merge your local `~/.m2`. See more [here](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local)

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 I'm not familiar even with what "Github Action workflow" means. I need to read about this. I think it's used for automated tasks here to verify that things work well? Might be useful. 
I just work a small SDK library and try to follow the instructions of how to use, or follow what's on the samples. 
After I fail to do this, I ask...
I'm very sorry that I've made you upset about my question. I already tried multiple things I thought of that are similar to the original repository, and as I saw that it was easy to migrate on a normal module, I was sure it will be as such on the AAR library module. I have both cases that I need to work on, and normal module works fine even with the newest gradle version of Canary Android Studio.

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 When you say that 0.5.0 isn't ready yet, does it mean I can't use previous version/s for AAR module?

**Comment by yujincheng08** [comment]
0.4.5 works. You can use 0.4.5 for it.

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 OK please let's continue on the original post:
https://github.com/LSPosed/LSParanoid/issues/8
