### ISSUE TITLE
Bug: LSParanoid doesn't obfuscate when used in an AAR Android library module

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [LSPosed/LSParanoid#8]
For a normal project, I succeeded to use LSParanoid just fine. I generated a signed APK file and I checked on a de-obfuscation tool that indeed I can't find the keys.

However, when I tried it on an Android library using the workarounds I was told ([here](https://github.com/LSPosed/LSParanoid/issues/7)), I could still see the values (of just the AAR library alone) not obfuscated.

Here's what I tried, and all failed:

1. Using this on either the library or the project that uses it causes a build-error:

```
classpath("org.lsposed.lsparanoid:gradle-plugin:0.4.5")
```

So I had to use this everywhere:

```
classpath("org.lsposed.lsparanoid:gradle-plugin:0.4.4")
```

2. I tried to use both 0.4.4 and 0.4.5 versions of this in the library:

```
implementation("org.lsposed.lsparanoid:core:XXX")
```

3. There was a workaround of not using "const", so I tried to add it and see what happens. After building, the generated aar and POM files were identical to what was before (meaning without "const").

Please help solve this.

An example of a file in the library that uses this:

```
import org.lsposed.lsparanoid.Obfuscate

@Suppress("MayBeConstant")
@Obfuscate
internal object SC {
    val SYNC_HEADER_KEY: String = "XsomeKey" 
}
```

When de-obfuscating, I didn't get "Deobfuscator" on this class. I could easily find the "XsomeKey" there...

**Comment by yujincheng08** [comment]
0.4.4 does not apply to library.

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 Please explain. What should I do exactly?

**Comment by yujincheng08** [comment]
0.4.4 only applies to com.android.application. it was fixed in 0.4.5.

**Comment by AndroidDeveloperLB** [comment]
What was fixed?
Please. I don't understand.
What should I have in the library's module, and what should I have in the app's module?

I already tried this :

```
implementation("org.lsposed.lsparanoid:core:0.4.5")
```

Now I'm trying "api... " instead. I hope it will solve it.

**Comment by AndroidDeveloperLB** [comment]
@yujincheng08 

I tried again:

In the library:

```
id 'org.lsposed.lsparanoid'
```

```
 classpath("org.lsposed.lsparanoid:gradle-plugin:0.4.4")
```

```
api 'org.lsposed.lsparanoid:core:0.4.5'
```

And not use "const" for things that should be obfuscated.

In the app that uses the library:

```
id 'org.lsposed.lsparanoid'
```

```
classpath("org.lsposed.lsparanoid:gradle-plugin:0.4.4")
```

Still, the keys in the AAR library file are not obfuscated.
Why does it happen? On the previous repository this workaround worked fine.

Please help

**Comment by AndroidDeveloperLB** [comment]
I also tried to remove what's on the app itself. Still didn't help. What's on the library is not obfuscated.

**Comment by yujincheng08** [comment]
You should see https://github.com/LSPosed/LSParanoid/tree/master/samples for better understanding.

**Comment by yujincheng08** [comment]
Also Github Action will show the obfuscation result of samples:
https://github.com/LSPosed/LSParanoid/actions/runs/4217151723

Cannot reproduce what you said about "library not obfuscated."
